### PR TITLE
improve precalculated curves, and uecm_stage2()

### PR DESCRIPTION
**Pull request by hurchalla**
Hi Ben -
I optimized the precalculated curve setup quite a bit - I think it probably makes sense to always have them enabled now (which I did).  I'm got about a 2-6% speedup from the new precalc'd curve changes, depending on the size of the number to factor.  As I recall, it was always a speedup to some extent.
The bigger changes were to uecm_stage2 function.  If you have time, could you review this?  I was going by intuition on these particular changes, rather than theory since I haven't properly studied ECM.  I verified the changes using all the semiprime test files from 42bit to 64bit that the uecm_stage2, that they caused no performance loss or test errors.  Nevertheless, I made substantial changes to this function essentially without knowing what I'm doing (intuition and tests notwithstanding).
The stage2 function changes *I think* provide greater clarity (which was my goal) and some simplifications and one or two really minor optimizations.  I think some of the comments had gone out of synch with the code, and in your ~30 line comment section I wrote some "note"s and questions - where it looked like those comments were wrong but I couldn't be sure.   If you have time, those notes would be good to look at and fix or remove.
Fyi, within uecm_stage2, I fixed a bug in the stg1_max == 70 case, where an out of date Paprod had been used - this wasn't causing errors but I think it did cause useless values to accumulate for a short while.  This small fix provided perhaps a 3% speedup for stg1_max of 70.

So in all, pretty modest perf gains, with the most gain coming for the small integers.

As before I built and tested locally using non-yafu functions so that I would have no dependencies (someday I'm going to just have to install GMP so that I can build yafu!).  Before committing, I restored the yafu function calls, so that there would (hopefully) be no trace of me doing a non-yafu build.  This is the same as last time, so nothing different this time, I just wanted to let you know in case you have any problem.

My instinct is microecm is in good shape at this point.  I really liked your precalc'd curves!

### CODE REVIEW

**Comment by hurchalla** [comment]
In case it saves time, It might help to know the very specific things I changed in uecm_stage2() where I used intuition rather than being confident of correctness ahead of time (i.e. changes where I had to rely on testing).

Those cases were solely the calls/changes I made to uecm_udup, and uecm_uadd.  I made two assumptions about these functions, which potentially might be wrong.  My assumption about uadd was that when it calculates (for some desired j)
[g]Q + [h]Q([k]Q) = [j]Q,
and that we must choose g, h, k, such that
g + h = j,  and
k = absolute_value(g - h).
Furthermore, I assumed any positive values of g,h,k can be used so long as they satisfy the requirements above (i.e. the resulting  [j]Q will be the same for any choice of  g,h,k  that satisfies those requirements).

I assumed about  udup  that for some positive value of m and known [m]Q, it calculates the result  [2m]Q.
Furthermore, I assumed [2m]Q  could alternatively and equivalently be calculated using uadd instead, so long as we set
j = 2m  and use valid choices of g,h,k  as described above for uadd.

If these assumptions are true, then I think all changes I made to uecm_stage2 should be good, since there wouldn't be any change based on an intuition (with testing).

**Comment by hurchalla** [comment]
FYI, I think the changes are likely already all good, since they passed tests with no losses to correctness or performance.
I mentioned the above in hopes to save you time.

**Comment by bbuhrow** [comment]
Thanks!  I knew the pre-built curves could likely be improved and thank you
for going through stage 2 so thoroughly.   I'll hopefully get a chance
tonight to go through your changes and merge them.

**Comment by bbuhrow** [comment]
Merged as-is.  I posted a new table of factorization timings on
mersenneforum.org.  Many thanks!

**Pull request merged**
